name: "Unit Tests"

on:
  pull_request:
    branches:
    - main
permissions:
  contents: write

defaults:
  run:
    shell: bash

jobs:
  shared-values:
    name: Shared Values
    runs-on: ubuntu-latest
    outputs:
      go-version: ${{ steps.set-go-version.outputs.go-version }}
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - id: set-go-version
      name: Parse Golang Version
      run: |
        go_version=($(grep -E '^go 1\.[[:digit:]]{1,2}' go.mod))
        echo "golang version: ${go_version[1]}"
        echo "::set-output name=go-version::${go_version[1]}"

  test:
    name: Running Unit Tests
    runs-on: ubuntu-latest
    needs: shared-values
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ needs.shared-values.outputs.go-version }}

      - name: Setup test
        run: |
          go install github.com/onsi/ginkgo/ginkgo@v1.16.4

      - name: Run Tests
        run: |
          export GOPATH=$HOME/cli-plugin-repo
          export PATH=$GOPATH/bin:$PATH
          bin/test
    env:
      BINARY_VALIDATION: false

